name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
     - run: |
        git remote add sync https://github.com/anshulktripathi/sync_repo_gmail
        git checkout main
        git pull
        git push sync -all
