name: Sync Files
on:
  push:
    branches:
      - branch2
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
     - run: |
        git remote add sync https://github.com/anshulktripathi/sync_repo_gmail.git
        git checkout branch2
        git pull
        git push sync -all
